In [1]:
!pip install matplotlib pandas sklearn numpy

In [2]:
import torch
torch.cuda.empty_cache()

In [ ]:
!pip install transformers simpletransformers

In [4]:
!pip list

Package                         Version              Editable project location
------------------------------- -------------------- ------------------------------------------------------------------------------------
absl-py                         0.15.0
aiofiles                        23.1.0
aiohttp                         3.8.4
aiosignal                       1.3.1
alabaster                       0.7.12
altair                          4.2.2
anaconda-client                 1.11.0
anaconda-navigator              2.3.1
anaconda-project                0.11.1
anyio                           3.5.0
appdirs                         1.4.4
argon2-cffi                     21.3.0
argon2-cffi-bindings            21.2.0
arrow                           1.2.2
astroid                         2.11.7
astropy                         5.1
astunparse                      1.6.3
async-timeout                   4.0.2
atomicwrites                    1.4.0
attrs                           21.4.0
Automat         

In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [6]:
data=pd.read_csv('dataset/wiki_movie.csv')

In [7]:
data.head()

Release Year                             Title Origin/Ethnicity  \
0          1901            Kansas Saloon Smashers         American   
1          1901     Love by the Light of the Moon         American   
2          1901           The Martyred Presidents         American   
3          1901  Terrible Teddy, the Grizzly King         American   
4          1902            Jack and the Beanstalk         American   

                             Director Cast    Genre  \
0                             Unknown  NaN  unknown   
1                             Unknown  NaN  unknown   
2                             Unknown  NaN  unknown   
3                             Unknown  NaN  unknown   
4  George S. Fleming, Edwin S. Porter  NaN  unknown   

                                           Wiki Page  \
0  https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1  https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2  https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3  https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4  https://en.wikipedia.org/wiki/Jack_and_the_Bea...   

                                                Plot  
0  A bartender is working at a saloon, serving dr...  
1  The moon, painted with a smiling face hangs ov...  
2  The film, just over a minute long, is composed...  
3  Lasting just 61 seconds and consisting of two ...  
4  The earliest known adaptation of the classic f...

Data Cleaning


In [8]:
data=data.drop(["Origin/Ethnicity","Director","Cast","Wiki Page"],axis=1)

In [9]:
import string
def drop_special_caracters(text):
    drop=''.join(char for char in text if char not in string.punctuation)
    return drop


data['Plot']=data['Plot'].apply(drop_special_caracters)


In [12]:
data['Genre']=data['Genre'].replace("unknown",'')

In [14]:
data

Release Year                             Title            Genre  \
0              1901            Kansas Saloon Smashers                    
1              1901     Love by the Light of the Moon                    
2              1901           The Martyred Presidents                    
3              1901  Terrible Teddy, the Grizzly King                    
4              1902            Jack and the Beanstalk                    
...             ...                               ...              ...   
34881          2014                 The Water Diviner                    
34882          2017                Çalgı Çengi İkimiz           comedy   
34883          2017                      Olanlar Oldu           comedy   
34884          2017                  Non-Transferable  romantic comedy   
34885          2017                İstanbul Kırmızısı         romantic   

                                                    Plot  
0      A bartender is working at a saloon serving dri...  
1      The moon painted with a smiling face hangs ove...  
2      The film just over a minute long is composed o...  
3      Lasting just 61 seconds and consisting of two ...  
4      The earliest known adaptation of the classic f...  
...                                                  ...  
34881  The film begins in 1919 just after World War I...  
34882  Two musicians Salih and Gürkan described the a...  
34883  Zafer a sailor living with his mother Döndü in...  
34884  The film centres around a young woman named Am...  
34885  The writer Orhan Şahin returns to İstanbul aft...  

[34886 rows x 4 columns]

In [15]:
df1 = pd.DataFrame({'Genre': data["Genre"], 'Plot': data["Plot"] , 'Date': data["Release Year"]})
evaluate_features=df1.apply(lambda x: ' '.join(x.astype('str')), axis=1)


In [16]:
data["evaluate_features"]=evaluate_features

In [17]:
data

Release Year                             Title            Genre  \
0              1901            Kansas Saloon Smashers                    
1              1901     Love by the Light of the Moon                    
2              1901           The Martyred Presidents                    
3              1901  Terrible Teddy, the Grizzly King                    
4              1902            Jack and the Beanstalk                    
...             ...                               ...              ...   
34881          2014                 The Water Diviner                    
34882          2017                Çalgı Çengi İkimiz           comedy   
34883          2017                      Olanlar Oldu           comedy   
34884          2017                  Non-Transferable  romantic comedy   
34885          2017                İstanbul Kırmızısı         romantic   

                                                    Plot  \
0      A bartender is working at a saloon serving dri...   
1      The moon painted with a smiling face hangs ove...   
2      The film just over a minute long is composed o...   
3      Lasting just 61 seconds and consisting of two ...   
4      The earliest known adaptation of the classic f...   
...                                                  ...   
34881  The film begins in 1919 just after World War I...   
34882  Two musicians Salih and Gürkan described the a...   
34883  Zafer a sailor living with his mother Döndü in...   
34884  The film centres around a young woman named Am...   
34885  The writer Orhan Şahin returns to İstanbul aft...   

                                       evaluate_features  
0       A bartender is working at a saloon serving dr...  
1       The moon painted with a smiling face hangs ov...  
2       The film just over a minute long is composed ...  
3       Lasting just 61 seconds and consisting of two...  
4       The earliest known adaptation of the classic ...  
...                                                  ...  
34881   The film begins in 1919 just after World War ...  
34882  comedy Two musicians Salih and Gürkan describe...  
34883  comedy Zafer a sailor living with his mother D...  
34884  romantic comedy The film centres around a youn...  
34885  romantic The writer Orhan Şahin returns to İst...  

[34886 rows x 5 columns]

In [ ]:
features=data["evaluate_features"].tolist()
features

Install sentence Transformer

In [ ]:
!pip install -U sentence-transformers

In [21]:
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
#Load pre-trained SentenceBERT model
model = SentenceTransformer('all-mpnet-base-v2')
#Get Embeddings
query_embedding = model.encode(features)


In [23]:
#similarity between movie features
cosine_scores = cosine_similarity(query_embedding)
print(cosine_scores)


[[1.         0.34266743 0.29599428 ... 0.2554754  0.28258947 0.15855007]
 [0.34266743 1.0000001  0.37714118 ... 0.3364394  0.33552223 0.30406386]
 [0.29599428 0.37714118 1.0000001  ... 0.20580417 0.23335248 0.21261898]
 ...
 [0.2554754  0.3364394  0.20580417 ... 1.0000002  0.43509778 0.49605846]
 [0.28258947 0.33552223 0.23335248 ... 0.43509778 1.         0.4168862 ]
 [0.15855007 0.30406386 0.21261898 ... 0.49605846 0.4168862  1.0000001 ]]


In [30]:
des=input("Enter the description of the movie for which you want recommendations: ")
year=input("Enter the year of release of the movie for which you want recommendations: ")
genre=input("Enter the genre of the movie for which you want recommendations: ")
k=int(input("Enter number of recommendations you want: "))



recommendations = sorted(list(enumerate(cosine_scores[data[data["Plot"] == des].index[0]])), key = lambda x:x[1], reverse = True)
print("The top "+str(k)+" recommendations for are: ", sep = "\n")
for i in range(0,k):
    print(data["Title"].loc[recommendations[i][0]])
    print("score:" +recommendations[i][1])
    print("\n")

Enter the description of the movie for which you want recommendations: A bartender is working at a saloon serving drinks to customers After he fills a stereotypically Irish mans bucket with beer Carrie Nation and her followers burst inside They assault the Irish man pulling his hat over his eyes and then dumping the beer over his head The group then begin wrecking the bar smashing the fixtures mirrors and breaking the cash register The bartender then sprays seltzer water in Nations face before a group of policemen appear and order everybody to leave1
Enter the year of release of the movie for which you want recommendations: 1901
Enter the genre of the movie for which you want recommendations: 
Enter number of recommendations you want: 5
The top 5 recommendations for are: 
Kansas Saloon Smashers
1.0


The Rounders
0.62635297


In Again, Out Again
0.57773995


Out West
0.5722094


All Woman
0.56905526


